//1.  let herors = ["saktiman", "ironman", "hulk"];
// 2. let marks=[96, 56, 86, 93];

// string => immatuable. array=> mutable

// 3. ARREY IS SPECIAL TYPE OF OBJECT... THAT'S HOLD KEY
//   (index) AND VALUE.

//4. ARRY INFORMAATION STORE KORAR EK LINER WAY.

//5. ARRY TE INDEX OR POSITION MATTER KKORE.

//6. marks.length => (LENGTH IS A PROPERTY) => VALUE.
     //MATHOUD ==> DO SOME WORK

// TO CHANGE VALUE OF ARRY==>